### ISSUE TITLE
About nix-darwin flake configuration switching

### ISSUE THREAD

**Issue by ghost** [hardselius/dotfiles#3]
Hi, I follow the README to setup my darwin flake configuration on my MacBook Air, after building bootstrap system then switching, report this error.
![截屏2021-02-08 上午10 13 18](https://user-images.githubusercontent.com/50952350/107168396-470f7a00-69f6-11eb-8beb-37918d015037.png)
I was saw the issue from [here](https://github.com/LnL7/nix-darwin/issues/274), I don't know how you solve the problem.

**Comment by hardselius** [comment]
Hi! Sorry for the late reply. I've not run into that issue myself. Have you made any progress on this?

**Comment by hardselius** [comment]
Your `/etc/synthetic.conf` looks off. It should contain

```
run	private/var/run
nix
```

while yours seem to contain

```
runtprivate/var/run
nix
```

**Comment by ghost** [comment]
@hardselius The problem is nix-darwin error, not identify \

**Comment by hardselius** [comment]
It actually seems like there's a problem with your `/etc/synthetic.conf`. You're getting

```
error: Directory /run does not exist, aborting activation
```

Your `synthetic.conf` needs to contain

```
run	private/var/run
```

That line creates a symbolic link named `run` at `/` which points to `/private/var/run`. You need to fix your `/etc/synthetic.conf` and then re-run the bootstrapping.

**Comment by ghost** [comment]
@hardselius I just modified /etc/synthetic.conf and now can bootstrapping. I'm tweaking the flake.nix to support the multi-platform now. Thanks. :)

**Comment by rpearce** [comment]
I had the same issue. I think it's because it's an escaped tab character. Check out all these examples:
https://github.com/search?q=run%5Ctprivate&type=code

Thanks for the correct fix!
